
spring :
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8082/
          predicates:
            - Path= /registration/**
        - id: r2
          uri: http://localhost:8083/
          predicates:
            - Path= /infractions/**
        - id: r3
          uri: http://localhost:8084/
          predicates:
            - Path= /radars/**